services:

  postgres:
    image: postgres:16-alpine
    container_name: dietetica-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dietetica
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  back-end:
    build: ./back-end
    container_name: dietetica-back
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    depends_on:
      - postgres
    volumes:
      - ./back-end:/back-end
      - /back-end/node_module

  front-end:
    build: ./front-end
    container_name: dietetica-front
    ports:
      - "5173:5173"
    env_file:
      - ./front-end/.env
    depends_on:
      - back-end
    volumes:
      - ./front-end:/app
      - /app/node_modules

volumes:
  postgres-data:
